# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonlist',
            name='node_id',
        ),
        migrations.AddField(
            model_name='addonlist',
            name='node',
            field=models.TextField(blank=True),
        ),
    ]
