# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_settings', to='addons_niirdccore.NodeSettings'),
        ),
    ]
