# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='dmr_api_key',
            field=models.TextField(blank=True),
        ),
    ]
