# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='dmp_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
