# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0002_auto_20210112_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonlist',
            name='addon_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addonlist',
            name='endpoint',
            field=models.CharField(max_length=50),
        ),
    ]
