# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-28 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0002_nodesettings_dmr_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesettings',
            name='dmr_api_key',
        ),
    ]
