# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-07 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0003_addonlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonlist',
            name='owner',
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='addon_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='endpoint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='project_id',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='AddonList',
        ),
    ]
