# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-07 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0004_auto_20210107_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('project_id', models.TextField(null=True)),
                ('addon_id', models.TextField(null=True)),
                ('endpoint', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_list', to='addons_niirdccore.AddonList')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='addon_id',
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='project_id',
        ),
    ]
