# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_niirdccore', '0004_auto_20210112_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonlist',
            name='addon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addonlist',
            name='endpoint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addonlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='addons_niirdccore.NodeSettings'),
        ),
    ]
